---

- name: Role_bind - Installing packages
  package:
    pkg: 
    - python3-netaddr
    - python3-dns
    - bind
    - bind-utils
    state: present
  become: yes


- name: Ensure runtime directories referenced in config exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0770
  become: yes
  with_items:
    - "{{ bind_dir }}/dynamic"
    - "{{ bind_dir }}/data"
    - "{{ bind_zone_dir }}"
  tags: bind







# This is where the config file is
# /etc/opt/isc/scls/isc-bind/named.conf